name: Build and Verify Sketch Publication

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install GPG
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf

      - name: Get GPG key ID
        id: gpg
        run: |
          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ {print $5}')
          echo "key_id=$KEY_ID" >> $GITHUB_OUTPUT

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish sketch to local Maven
        env:
          ORG_GRADLE_PROJECT_signing.gnupg.keyName: ${{ steps.gpg.outputs.key_id }}
          ORG_GRADLE_PROJECT_signing.gnupg.passphrase: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signing.gnupg.executable: gpg
          ORG_GRADLE_PROJECT_signing.gnupg.useLoopbackPinentry: true
        run: ./gradlew :sketch:publishToMavenLocal

      - name: Build app using published sketch
        run: |
          export GPG_TTY=$(tty)
          ./gradlew :app:assembleDebug
