name: Build and Verify Sketch Publication

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install GPG
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "default-key $(gpg --list-secret-keys --keyid-format=long | grep sec | head -n1 | awk '{print $2}' | cut -d'/' -f2)" >> ~/.gnupg/gpg.conf

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish sketch to local Maven
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew :sketch:publishToMavenLocal
          -Psigning.gnupg.keyName="$GPG_PRIVATE_KEY" \
          -Psigning.gnupg.passphrase="$GPG_PASSPHRASE" \
          -Psigning.gnupg.executable=gpg \
          -Psigning.gnupg.useLoopbackPinentry=true

      - name: Build app using published sketch
        run: ./gradlew :app:assembleDebug
